import type {Config} from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        code: ['monospace'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          'color-1': 'hsl(var(--chart-color-1))',
          'color-2': 'hsl(var(--chart-color-2))',
          'color-3': 'hsl(var(--chart-color-3))',
          'color-4': 'hsl(var(--chart-color-4))',
          'color-5': 'hsl(var(--chart-color-5))',
          'color-6': 'hsl(var(--chart-color-6))',
          'color-7': 'hsl(var(--chart-color-7))',
          'color-8': 'hsl(var(--chart-color-8))',
          'color-9': 'hsl(var(--chart-color-9))',
          'color-10': 'hsl(var(--chart-color-10))',
          'color-11': 'hsl(var(--chart-color-11))',
          'color-12': 'hsl(var(--chart-color-12))',
          'color-13': 'hsl(var(--chart-color-13))',
          'color-14': 'hsl(var(--chart-color-14))',
          'color-15': 'hsl(var(--chart-color-15))',
          'color-16': 'hsl(var(--chart-color-16))',
          'color-17': 'hsl(var(--chart-color-17))',
          'color-18': 'hsl(var(--chart-color-18))',
          'color-19': 'hsl(var(--chart-color-19))',
          'color-20': 'hsl(var(--chart-color-20))',
          'color-21': 'hsl(var(--chart-color-21))',
          'color-22': 'hsl(var(--chart-color-22))',
          'color-23': 'hsl(var(--chart-color-23))',
          'color-24': 'hsl(var(--chart-color-24))',
          'color-25': 'hsl(var(--chart-color-25))',
          'color-26': 'hsl(var(--chart-color-26))',
          'color-27': 'hsl(var(--chart-color-27))',
          'color-28': 'hsl(var(--chart-color-28))',
          'color-29': 'hsl(var(--chart-color-29))',
          'color-30': 'hsl(var(--chart-color-30))',
          'color-31': 'hsl(var(--chart-color-31))',
          'color-32': 'hsl(var(--chart-color-32))',
          'color-33': 'hsl(var(--chart-color-33))',
          'color-34': 'hsl(var(--chart-color-34))',
          'color-35': 'hsl(var(--chart-color-35))',
          'color-36': 'hsl(var(--chart-color-36))',
          'color-37': 'hsl(var(--chart-color-37))',
          'color-38': 'hsl(var(--chart-color-38))',
          'color-39': 'hsl(var(--chart-color-39))',
          'color-40': 'hsl(var(--chart-color-40))',
          'color-41': 'hsl(var(--chart-color-41))',
          'color-42': 'hsl(var(--chart-color-42))',
          'color-43': 'hsl(var(--chart-color-43))',
          'color-44': 'hsl(var(--chart-color-44))',
          'color-45': 'hsl(var(--chart-color-45))',
          'color-46': 'hsl(var(--chart-color-46))',
          'color-47': 'hsl(var(--chart-color-47))',
          'color-48': 'hsl(var(--chart-color-48))',
          'color-49': 'hsl(var(--chart-color-49))',
          'color-50': 'hsl(var(--chart-color-50))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
