// This file is automatically generated. Do not modify it manually.
// This is a public configuration and is safe to be exposed to the client.

export const firebaseConfig = {
  apiKey: "AIzaSyCV7Tz2m3L7W7vK82EAEyk9yE_EXAMPLE",
  authDomain: "prempred-43933.firebaseapp.com",
  projectId: "prempred-43933",
  storageBucket: "prempred-43933.appspot.com",
  messagingSenderId: "54228994464",
  appId: "1:54228994464:web:d25d2c8035a0921383858c",
  databaseURL: "https://prempred-43933.firebaseio.com"
};
