import {
  Trophy,
  PenSquare,
  Calculator,
  User,
  Bell,
  BrainCircuit,
  LucideProps,
  Shield,
  Bird,
  Ship,
  Sparkles,
  Swords,
  ChevronUp,
  ChevronDown,
  Minus,
  ListOrdered,
  Award,
  BarChart,
  Users,
  TrendingUp,
  Cherry,
  Bee,
  Lion,
  Castle,
  Horse,
  CircleDot,
  Tree,
  Flower,
  Hammer,
  Wolf,
} from 'lucide-react';

export const Icons = {
  logo: BrainCircuit,
  leaderboard: Trophy,
  predict: PenSquare,
  scoring: Calculator,
  standings: ListOrdered,
  stats: BarChart,
  consensus: Users,
  profile: User,
  notifications: Bell,
  award: Award,
  performance: BarChart,
  rankings: TrendingUp,
  shield: Shield,
  bird: Bird,
  ship: Ship,
  sparkles: Sparkles,
  swords: Swords,
  cherry: Cherry,
  bee: Bee,
  lion: Lion,
  castle: Castle,
  horse: Horse,
  fox: CircleDot,
  tree: Tree,
  flower: Flower,
  hammer: Hammer,
  wolf: Wolf,
  match: Swords,
  rankUp: (props: LucideProps) => <ChevronUp {...props} className="text-green-500" />,
  rankDown: (props: LucideProps) => <ChevronDown {...props} className="text-red-500" />,
  rankSame: (props: LucideProps) => <Minus {...props} className="text-gray-500" />,
};

export type IconName = keyof typeof Icons;
