import {
  Trophy,
  PenSquare,
  Calculator,
  User,
  Bell,
  BrainCircuit,
  LucideProps,
  Shield,
  Bird,
  Ship,
  Sparkles,
  Swords,
  ChevronUp,
  ChevronDown,
  Minus,
  ListOrdered,
  Award,
  BarChart,
  Users,
  TrendingUp,
  Cherry,
  Castle,
  CircleDot,
  Trees,
  Flower,
  Hammer,
  Drill,
  Squirrel,
  Fingerprint,
  Bug,
  ShieldUser,
  CreativeCommons,
  Rabbit,
  Home,
  ShieldHalf,
  MapPin,
  Origami,
  Sailboat,
  Menu,
  TreeDeciduous,
  Theater,
  UtensilsCrossed,
  Gitlab,
} from 'lucide-react';

export const Icons = {
  logo: BrainCircuit,
  leaderboard: Trophy,
  predict: PenSquare,
  scoring: Calculator,
  standings: ListOrdered,
  stats: BarChart,
  consensus: Users,
  profile: User,
  notifications: Bell,
  award: Award,
  performance: BarChart,
  rankings: TrendingUp,
  shield: Shield,
  bird: Bird,
  ship: Ship,
  sparkles: Sparkles,
  swords: Swords,
  cherry: Cherry,
  castle: Castle,
  flower: Flower,
  hammer: Hammer,
  trees: Trees,
  drill: Drill,
  squirrel: Squirrel,
  fingerprint: Fingerprint,
  bug: Bug,
  twitter: Bird,
  shieldUser: ShieldUser,
  creativeCommons: CreativeCommons,
  rabbit: Rabbit,
  houseWifi: Home,
  shieldHalf: ShieldHalf,
  mapPin: MapPin,
  origami: Origami,
  sailboat: Sailboat,
  hamburger: Menu,
  chessRook: Castle,
  treeDeciduous: TreeDeciduous,
  theatre: Theater,
  utensilsCrossed: UtensilsCrossed,
  gitlab: Gitlab,
  bee: Bug,
  lion: Shield,
  horse: Shield,
  wolf: Shield,
  match: Swords,
  rankUp: (props: LucideProps) => <ChevronUp {...props} className="text-green-500" />,
  rankDown: (props: LucideProps) => <ChevronDown {...props} className="text-red-500" />,
  rankSame: (props: LucideProps) => <Minus {...props} className="text-gray-500" />,
};

export type IconName = keyof typeof Icons;
